### ISSUE TITLE
Set access to to report invoice

### ISSUE THREAD

**Issue by ZSimon** [MewsSystems/fiscalization-hungary#58]
Hi,

do you have some test certificate and login that I can test the code?
And can you explain how do you set environmental variables? Probably you have to extract the key from p12 or pfx file?
`       private static readonly Login Login = new Login(Environment.GetEnvironmentVariable("login") ?? "INSERT_LOGIN");
        private static readonly string Password = Environment.GetEnvironmentVariable("password") ?? "INSERT_PASSWORD";
        private static readonly SigningKey SigningKey = new SigningKey(Environment.GetEnvironmentVariable("signing_key") ??"INSERT_SIGNING_KEY");
        private static readonly EncryptionKey EncryptionKey = new EncryptionKey(Environment.GetEnvironmentVariable("encryption_key") ?? "INSERT_ENCRYPTION_KEY")`

Thank you

**Comment by abdallahbeshi** [comment]
Hi ZSimon,

In order to obtain the test (Technical user information), you'll have to register at https://onlineszamla-test.nav.gov.hu/home, and then you need to head to "Online Invoicing Programme" and there you can find the technical user informations that are needed in order to use the library and start reporting invoices.

You will either have to set up the environment variables as defined in the code or replace the text "INSERT_...." with the values obtained from the government website.

That's how the values are represented in the library and the government website:
Login = Username
Password = Password
SigningKey = XML Signature Key
EncryptionKey = XML Exchange Key

You can also find the technical documentation on the website provided above.

Thanks.

**Comment by ZSimon** [comment]
Thank you Abdallah,

I thought there is also some global test user which I can use before
getting registration.

I will wait then.

Br, Simon

**Comment by ZSimon** [comment]
Hi Abdulah,

I hava managed to get technical data but when I try to run the test invoice I get the following error at setting tax-payer_id:

`private static readonly TaxpayerIdentificationNumber TaxPayerId = TaxpayerIdentificationNumber.Create(Countries.Hungary, Environment.GetEnvironmentVariable("tax_payer_id") ?? "28092061-2-43").Success.Get();`

System.InvalidOperationException : An empty option does not have a value

Do you have any idea what this error could be?

br, Simon

**Comment by abdallahbeshi** [comment]
@ZSimon `28092061-2-43` is an invalid HU taxpayer id. HU taxpayer ids should contain only 9 numbers, so I believe if you remove the `-2-43` part, it should work.

Abdallah

**Comment by KaliCZ** [comment]
Yes, the `.Success` property of an ITry is an IOption. And calling `.Get()` on an option is a bad idea. It means that you're very sure that the option has value. Therefore it should only be used in cases like this - setting up static variables. 

You can find more about options, tries and other algebraic types here - https://github.com/siroky/FuncSharp. 

But simplified version is - make sure your taxIdentifier is correct 😄

**Comment by ZSimon** [comment]
Thanks,

you are right, only 9 numbers should be.
That format of tax id was given to me from my accounting. I have also
checked here and all tax numbers are "xxxxxxxxx-x-xx".

https://www.companyregister.hu/?Search%5Bfilename%5D=p405d4i1641&Search%5BStype%5D=CgnevKeres&Search%5Bcegnev%5D=studio&Search%5Bcaptcha%5D=xosidz

And that tricked me. But now it is all clear.

**Comment by ZSimon** [comment]
Thank you Pavel for clarification.
This Get has been added at last version.
I will read more about it.

Have a nice day.

**Comment by ZSimon** [comment]
When I post to get exchange token:
`https://api-test.onlineszamla.nav.gov.hu/invoiceService/v2/tokenExchange`

I get this error: INVALID_SECURITY_USER

I use login, password, signing key and encryption key as I got from registration.
I use software identification as it is:
`               id: "123456789123456789",
                name: "Test",
                type: SoftwareType.LocalSoftware,
                mainVersion: "1.0",
                developerName: "Test",
                developerContact: "test@test.com"`

I guess for test this data can be random?

So, probably the problem is with tehnical user data - do you maybe know what field exactly? I have searched the documentation but didn't find which field exactly is wrong when you get this error.
