### ISSUE TITLE
Customer info data

### ISSUE THREAD

**Issue by ZSimon** [MewsSystems/fiscalization-hungary#61]
When I try to send new invoice to authorities, your invoice class requires to set "customerInfo" in constructor.
But "customerInfo" is not mandatory data(from documentation). Also many shops doesn't take customer tax number and address. Usually you don't have this data.
Can you set customerInfo as optional and if not set that it can be exempt from request? 
I guess I can't set all data as empty string?

`                

                  <customerInfo>

                    <customerTaxNumber>

                    <taxpayerId></taxpayerId>

                    </customerTaxNumber>

                    <customerName></customerName>

                    <customerAddress>

                        <simpleAddress>

                            <countryCode></countryCode>

                            <postalCode></postalCode>

                            <city></city>

                            <additionalAddressDetail></additionalAddressDetail>

                        </simpleAddress>

                    </customerAddress>

                </customerInfo>`

Thanks

**Comment by abdallahbeshi** [comment]
Hi ZSimon,

The field `customerInfo` is actually required and the invoices will not be submitted successfully without providing it in the request.

Please check page '272 251' in the [documentation] (https://onlineszamla.nav.gov.hu/api/files/container/download/Online%20Szamla_Interfesz%20specifik%C3%A1ci%C3%B3_EN_v2.0.pdf) 
![image](https://user-images.githubusercontent.com/51375082/107193213-e3358300-69ee-11eb-950f-594eb78fcd2b.png)

Also, you can remove the `customerInfo` from the tests and debug the response from the government, you will notice that they return a response with "error" status and a message that says "Customer information must be provided."

Have a nice day!
Abdallah

**Comment by ZSimon** [comment]
I have been looking at 85 10 page where it is a description of Invoice Head and there it is not required:
![image](https://user-images.githubusercontent.com/5880095/107200437-fd279380-69f7-11eb-9160-d4cd338234e7.png)

I would try to test with requests but I can't since I'm still getting an error: "INVALID SECURITY USER" when sending request ti get the token which is required prior sending invoice request. I have contacted authorities already but still didn't get any answer. Also many other Hungarian companies have the same problem. Even after creating new technical user still the same. So, until further, I'm coding without being able to test :(

Well, there is probably no shop which would require tax number and address from customer if you wan't to buy something.
It must be the way to send invoice without customer info, since there are many shops without having tax number and other data from customer.
Is it allowed to send empty string as customer tax number and empty string as address and customer name?
I guess not, since you have also checking of correct tax number in your code, while NULL is also not allowed. 
It should be somehow excluded from request if it is not known.
Does it allow maybe to send empty customerInfo tag `<customerInfo></customerInfo>?`

So, can you just check how to send invoice in your code without customer info (maybe just empty tag would be fine) since most of shops doesn't have this data? Probably others will have the same problem as I have.
I will check also with other companies.

**Comment by ZSimon** [comment]
Hi Abdallah

i have checked again, on page 272 customerInfo is required, but TaxNumber, address, name,... no other data is required:
![image](https://user-images.githubusercontent.com/5880095/107341037-cc5e6180-6abe-11eb-9b03-e0b53ddc9c4f.png)


You info class requires TayPayerid, Name and Address to be set even if they are not required:

`        public Info(TaxpayerIdentificationNumber taxpayerId, Name name, SimpleAddress address)
        {
            TaxpayerId = Check.IsNotNull(taxpayerId, nameof(taxpayerId));
            Name = Check.IsNotNull(name, nameof(name));
            Address = Check.IsNotNull(address, nameof(address));
        }`

Can you change the code that this data is optional as it should be?
I will also try but you are the author of all :)

br, Simon

**Comment by KaliCZ** [comment]
@ZSimon I understand that you want to not provide the data. But I'd wait with the removal until you actually get your credentials and are able to verify that the request works even without this data. 

Generally when we add a validation that means it is actually required. So the server will not accept not providing the value. It is possible that has changed and you are right. But then that would be an easy fix. So I'd say let's wait till it's confirmed and then we can make the change. (Or you can open a PR making it optional) 

But if we're changing our code, it needs to always work. There must not be any single scenario where it would not be allowed. And at this moment it doesn't appear that we are sure it's optional. There is some conflicting proof, so I'm not convinced.

**Comment by ZSimon** [comment]
Thank you Pavel,

I have already changed it to be optional. But I don't know if it works
since I can't test it.
If it will work I will open PR. I'm 100% sure that customer tax number
can't be required, since shops usually don't have it.
