### ISSUE TITLE
Transaction status error parsing

### ISSUE THREAD

**Issue by ZSimon** [MewsSystems/fiscalization-hungary#63]
Hi,

you have set 3 seconds to wait for the result of your invoice generation:

`Thread.Sleep(3000);
var transactionStatus = await navClient.GetTransactionStatusAsync(invoiceTransactionId.SuccessResult);`

What if status is still receiving after 3 seconds? Maybe there should be some separate service to check the results of each invoice until status is DONE or ABORTED? Or maybe set thread to 1 second and read the result until Done or Aborted - what do you suggest?

When sending your test case, I'm getting invoice status as DONE but with many warnings.
I guess there should be thrown error in this case and fiscalization should be manually repeated later with corrected invoice?

So, there should be first check for status:

`                    var status=transactionStatus.SuccessResult.InvoiceStatuses[0].Value.Status;
                    if (status == InvoiceState.Aborted)
                        throw new Exception("");`

And then if staus is ok(DONE or SAVED), check if some of the validation results has Warning, since that means invoice should be corrected?
`transactionStatus.SuccessResult.InvoiceStatuses[0].Value.ValidationResults`

How do you deal with that, do you have some solution?

This is the XML result set:

`<processingResults><processingResult><index>1</index><invoiceStatus>DONE</invoiceStatus><businessValidationMessages><validationResultCode>WARN</validationResultCode><validationErrorCode>INCORRECT_LINE_CALCULATION_AGGREGATE_LINE_UNIT_PRICE_HUF</validationErrorCode><message>Eltérés a gyűjtőszámla tétel eredeti pénznemben és forintban megadott egységára között.</message><pointer><tag>InvoiceData/invoiceMain/invoice/invoiceLines/line/unitPriceHUF</tag><value>19</value><line>1</line></pointer></businessValidationMessages><businessValidationMessages><validationResultCode>WARN</validationResultCode><validationErrorCode>INCORRECT_LINE_CALCULATION_AGGREGATE_LINE_UNIT_PRICE_HUF</validationErrorCode><message>Eltérés a gyűjtőszámla tétel eredeti pénznemben és forintban megadott egységára között.</message><pointer><tag>InvoiceData/invoiceMain/invoice/invoiceLines/line/unitPriceHUF</tag><value>19</value><line>2</line></pointer></businessValidationMessages><businessValidationMessages><validationResultCode>WARN</validationResultCode><validationErrorCode>INCORRECT_SUMMARY_CALCULATION_INVOICE_GROSS_AMOUNT_HUF_SUMMARY</validationErrorCode><message>A számlaösszesítő nettó és áfaértékek összege forintban eltér a számla forintban feltüntetett bruttó értékétől. </message><pointer><tag>InvoiceData/invoiceMain/invoice/invoiceSummary/summaryGrossData/invoiceGrossAmountHUF</tag><value>6.38</value></pointer></businessValidationMessages><businessValidationMessages><validationResultCode>WARN</validationResultCode><validationErrorCode>INCORRECT_SUMMARY_CALCULATION_INVOICE_GROSS_AMOUNT_SUMMARY</validationErrorCode><message>A számlaösszesítő nettó és áfaértékek összege eltér a számla bruttó értékétől.</message><pointer><tag>InvoiceData/invoiceMain/invoice/invoiceSummary/summaryGrossData/invoiceGrossAmount</tag><value>6.38</value></pointer></businessValidationMessages><businessValidationMessages><validationResultCode>WARN</validationResultCode><validationErrorCode>INCORRECT_LINE_CALCULATION_NET_AMOUNT</validationErrorCode><message>A tétel mennyiség és egységár szorzata (figyelembe véve az adott kedvezményt) eltér a nettó értékétől.</message><pointer><tag>InvoiceData/invoiceMain/invoice/invoiceLines/line/lineAmountsNormal/lineNetAmountData/lineNetAmount</tag><value>14</value><line>1</line></pointer></businessValidationMessages><businessValidationMessages><validationResultCode>WARN</validationResultCode><validationErrorCode>INCORRECT_LINE_CALCULATION_NET_AMOUNT</validationErrorCode><message>A tétel mennyiség és egységár szorzata (figyelembe véve az adott kedvezményt) eltér a nettó értékétől.</message><pointer><tag>InvoiceData/invoiceMain/invoice/invoiceLines/line/lineAmountsNormal/lineNetAmountData/lineNetAmount</tag><value>5</value><line>2</line></pointer></businessValidationMessages><businessValidationMessages><validationResultCode>WARN</validationResultCode><validationErrorCode>INCORRECT_SUMMARY_CALCULATION_VAT_RATE_VAT_AMOUNT_HUF_SUMMARY</validationErrorCode><message>Az áfa-mértékhez tartozó nettó összegből és az alkalmazott adó mértékből számított áfaösszeg forintban eltér a forintban feltüntetett áfaösszegtől. </message><pointer><tag>InvoiceData/invoiceMain/invoice/invoiceSummary/summaryNormal/summaryByVatRate/vatRateVatData/vatRateVatAmountHUF</tag><value>2.14</value></pointer></businessValidationMessages><businessValidationMessages><validationResultCode>WARN</validationResultCode><validationErrorCode>INCORRECT_SUMMARY_CALCULATION_VAT_RATE_VAT_AMOUNT_SUMMARY</validationErrorCode><message>Az áfa-mértékhez tartozó nettó összegből és az alkalmazott adómértékből számított áfaösszeg eltér a feltüntetett áfaösszegtől.</message><pointer><tag>InvoiceData/invoiceMain/invoice/invoiceSummary/summaryNormal/summaryByVatRate/vatRateVatData/vatRateVatAmount</tag><value>2.14</value></pointer></businessValidationMessages><businessValidationMessages><validationResultCode>WARN</validationResultCode><validationErrorCode>INCORRECT_DATE_INVOICE_ISSUE_DATE_EARLY</validationErrorCode><message>Számla kelte több, mint 15 nappal korábbi, mint az adatszolgáltatás dátuma.</message><pointer><tag>InvoiceData/invoiceIssueDate</tag><value>2020-06-30</value></pointer></businessValidationMessages><compressedContentIndicator>false</compressedContentIndicator></processingResult>`

**Comment by KaliCZ** [comment]
Hi ,

1. The 3  seconds - Yes, we used thread sleep. That's because it's only used for tests. In a real-world scenario you should of course have a proper asynchronous workflow that would periodically check for results until you actually get one. 

2. Again, in a real world scenario, yes you can handle warnings. I don't think throwing exception is a good idea, but in general: yes, customers should correct the invoices. Our library doesn't have endpoints for updating of existing invoices, so you would need to read the official documentation and extend the library with this support. 
So as to how we deal with it: we just display the warnings to the users and then advise them to go to the portal and update it manually if needed. 

But of course if somebody would receive the errors you are getting (incorrect tax calculation etc.) we would be fixing the code to prevent these errors from happening.
