### ISSUE TITLE
Invoice with discount

### ISSUE THREAD

**Issue by ZSimon** [MewsSystems/fiscalization-hungary#65]
Hi,
When I would like to send invoice with discountValue it works. Example, when discount is 50 forint for example:
`fisk.AddInvoiceItem("20210321", "Item1", 7873m, 1, 7823m, 9935m, 0.27m, 50m);`

Now I have example when discount is 100% and net and gross value is 0:

`fisk.AddInvoiceItem("20210321", "Item1", 7873m, 1, 0m, 0m, 0.27m, 7873m);`

I get an error from fiskal service:
"The product of the quantity of the item and the unit price (taking into account the given discount) differs from its net value."

So, how can I send invoice with 100% discount?

Thank you,
Simon

**Comment by KaliCZ** [comment]
@ZSimon Hey, I'm sorry, but I can't give you the answer to that. 
- This is your method. We don't know what it does.
- The error message you are getting is also not coming from us, but most like from the server I assume?
- We're not the government. We didn't write the API. We don't know what are some of the validations that are being done and why they are being done. 

So basically I know less than you at this moment and can't help you.
